default_provider = "base"

[providers.base]
type = "age"
recipients = ["age1xftywypm2dl6aw22f476latekvhy4tvn8v8myka2k2h8x2wyf5zq694k3r"]

[secrets]
TELEGRAM_API_TOKEN = { provider = "base", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SlJyVkpybEh2N04wWEorcWhjTGFXT2Vvd0tQbUJ1cld0UFA4cTdOTERFCnN6N09QKzJQaGd3cjlDQ0JlenppNzR0eTRzamJTbmVBd3RYWHAyYlNIM0kKLT4gYWcuLWdyZWFzZSBLMV4gZ14KUDZUYWZ0T3hTWkFLS01WcFZycGdZY28KLS0tIGZtWlU1a0tQWkZmKzJuclAyMWVoREFoTFowUEhWOEVFNGxzYWJ3bVFvbEEKOsrr2d2dRKrZ/akHr5pIcYWWFAQf5A5w8DD8a6MdiHbcL53QRYbXQUMelF75g4Bvq24nb1O4rrKXNuT6S3lOrFiQTK+tnqWFRzoI7E7G" }
